name: flutter_gemma_notes
description: A Flutter notes app with AI-powered text rewriting, summarizing, and paraphrasing using Gemma 3
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  flutter_markdown: ^0.6.18
  provider: ^6.1.1
  path_provider: ^2.1.1
  dio: ^5.4.0
  sqflite: ^2.3.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
